FROM node:18-alpine

ARG MONGODB_URI
ARG MODEL_URL
ARG PORT
ARG CLOUDINARY_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET

ENV MONGODB_URI=${MONGODB_URI}
ENV MODEL_URL=${MODEL_URL}
ENV PORT=${PORT}
ENV CLOUDINARY_NAME=${CLOUDINARY_NAME}
ENV CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
ENV CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

WORKDIR /app
COPY package*.json ./
COPY . .
RUN npm install
# RUN npm run build

EXPOSE 2000
CMD ["node", "server.js"]